# app/db/models.py
# Database table definitions using SQLAlchemy ORM.
# Each class here represents one table in PostgreSQL.
# Tables: Profile, PipelineRun, Query, Recommendation

import uuid
from datetime import datetime
from sqlalchemy import (
    Column, String, Text, Float, Integer,
    Boolean, DateTime, ForeignKey, JSON
)
from sqlalchemy.orm import declarative_base, relationship

# Base class that all models will inherit from
Base = declarative_base()


def generate_uuid():
    """Generate a new unique ID for each database row."""
    return str(uuid.uuid4())


class Profile(Base):
    """
    Stores brand profiles registered by the user.
    Example: Surfer SEO, domain: surferseo.com
    """
    __tablename__ = "profiles"

    id = Column(String, primary_key=True, default=generate_uuid)
    name = Column(String(255), nullable=False)
    domain = Column(String(255), nullable=False)
    industry = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)
    competitors = Column(JSON, default=list)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # One profile can have many pipeline runs
    runs = relationship("PipelineRun", back_populates="profile")


class PipelineRun(Base):
    """
    Stores each DAG pipeline execution for a profile.
    One profile can have multiple runs over time.
    """
    __tablename__ = "pipeline_runs"

    id = Column(String, primary_key=True, default=generate_uuid)
    profile_id = Column(String, ForeignKey("profiles.id"), nullable=False)

    # Status: completed / failed / partial
    status = Column(String(50), default="running")

    # Summary counts
    retrieval_calls_planned = Column(Integer, default=0)
    records_extracted = Column(Integer, default=0)
    total_tokens_used = Column(Integer, default=0)

    # Final report stored as JSON
    report = Column(JSON, nullable=True)

    # Error details if run failed
    error_message = Column(Text, nullable=True)

    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    profile = relationship("Profile", back_populates="runs")
    queries = relationship("Query", back_populates="run")
    recommendations = relationship("Recommendation", back_populates="run")


class Query(Base):
    """
    Stores each search query planned by the Query Planner agent.
    Example: "best SEO tool", "surfer seo review"
    """
    __tablename__ = "queries"

    id = Column(String, primary_key=True, default=generate_uuid)
    run_id = Column(String, ForeignKey("pipeline_runs.id"), nullable=False)
    profile_id = Column(String, ForeignKey("profiles.id"), nullable=False)

    # The actual search term
    query_text = Column(String(500), nullable=False)

    # Search volume and difficulty
    estimated_search_volume = Column(Integer, default=0)
    competitive_difficulty = Column(Integer, default=0)  # 0-100

    # Opportunity score calculated by Analyzer agent (0.0 - 1.0)
    opportunity_score = Column(Float, default=0.0)

    # Visibility data from DataForSEO
    domain_visible = Column(Boolean, default=False)
    visibility_position = Column(Integer, nullable=True)
    visibility_status = Column(String(50), default="unknown")

    discovered_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    run = relationship("PipelineRun", back_populates="queries")
    recommendations = relationship("Recommendation", back_populates="query")


class Recommendation(Base):
    """
    Stores content recommendations generated by the Analyzer agent.
    Each recommendation targets a specific query visibility gap.
    """
    __tablename__ = "recommendations"

    id = Column(String, primary_key=True, default=generate_uuid)
    run_id = Column(String, ForeignKey("pipeline_runs.id"), nullable=False)
    profile_id = Column(String, ForeignKey("profiles.id"), nullable=False)
    query_id = Column(String, ForeignKey("queries.id"), nullable=True)

    # Content type: blog_post / landing_page / faq
    content_type = Column(String(100), nullable=False)

    # Suggested content title
    title = Column(String(500), nullable=False)

    # Why this content will help
    rationale = Column(Text, nullable=False)

    # Target keywords as JSON array
    target_keywords = Column(JSON, default=list)

    # Priority: high / medium / low
    priority = Column(String(20), default="medium")

    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    run = relationship("PipelineRun", back_populates="recommendations")
    query = relationship("Query", back_populates="recommendations")