# app/api/routes/recommendations.py
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.session import get_db
from app.db.crud import get_recommendations, get_profile
from app.api.schemas.query import RecommendationResponse

router = APIRouter()


@router.get("/profiles/{profile_uuid}/recommendations", response_model=list[RecommendationResponse])
def get_profile_recommendations(profile_uuid: str, db: Session = Depends(get_db)):
    """
    Return all content recommendations for a profile.
    Generated by the Analyzer and assembled by the Report agent.
    """
    profile = get_profile(db, profile_uuid)
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")

    recommendations = get_recommendations(db, profile_uuid)

    return [
        RecommendationResponse(
            recommendation_uuid=r.id,
            target_query_uuid=r.query_id,
            content_type=r.content_type,
            title=r.title,
            rationale=r.rationale,
            target_keywords=r.target_keywords or [],
            priority=r.priority
        )
        for r in recommendations
    ]