# app/graph/state.py
from typing import TypedDict, Optional


class PipelineState(TypedDict):
    # Brand profile info passed at the start
    profile: dict

    # Run ID to track this execution in the database
    run_id: str

    # Queries generated by the Planner agent
    planned_queries: list

    # Raw data fetched by the Retrieval agent from DataForSEO
    raw_results: list

    # Cleaned and structured data from the Extractor agent
    normalized_data: list

    # Insights and opportunity scores from the Analyzer agent
    insights: list

    # Final report assembled by the Report agent
    final_report: dict

    # Pipeline status: running / completed / failed / partial
    status: str

    # Any errors encountered during the run
    errors: list

    # Total tokens used by LLM calls
    total_tokens_used: int